### PR TITLE
Issue 28 grunt task updates

### PR DESCRIPTION
**Pull request by windycitymoon**
Updates on this branch will allow for Patternlab auto-reloading in Gesso.

To test, check this branch out and then

1. Install a Patternlab instance
$ composer create-project pattern-lab/edition-drupal-standard pattern-lab

2. Make sure you have all the new node modules installed.
$ npm install

This has been tested to run in tandem with a Vagrant box. This update spins up a separate server for the Patternlab instance.

*Please note that because of a known issue with the grunt-contrib-connect task you must use a full path when defining the pattern-lab location inside of the grunt watch task. A note has been included there.

*This approach should work for the Drupal Gesso theme as well.

Handles #28

### CODE REVIEW

**Comment by dmoon79** [comment]
@lrobeson 
@cssgirl 
@karenkitchens 

Patternlab auto-reloading via grunt. In case you are interested.

**Comment by coreylafferty** [comment]
@elvismdev @dmoon79 I'll need to give this a closer look and coordinate with Dan about this.  I want to keep the grunt tasks between the Drupal and WP versions identical, if at all possible, so we'd need to add this to the D8 version as well.

Is there no way to use the package variable in the path?  Without that things would get more complicated b/c we'd need to manually edit the tasks when they are moved out of the theme directory and added to the vagrant project root.

**Comment by dmoon79** [comment]
@coreylafferty That makes sense. Using package.json variables in the path causes an error where any newly created PL twig files don't appear on the refresh. The server needs to be restarted in that case. 

The work that @mortona42 and @elvismdev have been doing with the Wordpress Yeoman generator, and the Jenkins deployment script may render this concern invalid. If Patternlab is setup up relative to the theme folder, that path for either version of Gesso could theoretically just be set at './'

**Comment by coreylafferty** [comment]
Closing.  Browsersync (or something similar) will be added once Gesso 2.0 changes are implemented.

**Pull request closed without merging**
